N = int(input())

if N == 0:
    print(" * * *")
    print("*     *")
    print("*     *")
    print("*     *")
    print()
    print("*     *")
    print("*     *")
    print("*     *")
    print(" * * *")
elif N == 1:
    print()
    print("      *")
    print("      *")
    print("      *")
    print()
    print("      *")
    print("      *")
    print("      *")
    print()
elif N == 2:
    print(" * * *")
    print("      *")
    print("      *")
    print("      *")
    print(" * * *")
    print("*")
    print("*")
    print("*")
    print(" * * *")
elif N == 3:
    print(" * * *")
    print("      *")
    print("      *")
    print("      *")
    print(" * * *")
    print("      *")
    print("      *")
    print("      *")
    print(" * * *")
elif N == 4:
    print()
    print("*     *")
    print("*     *")
    print("*     *")
    print(" * * *")
    print("      *")
    print("      *")
    print("      *")
    print()
elif N == 5:
    print(" * * *")
    print("*")
    print("*")
    print("*")
    print(" * * *")
    print("      *")
    print("      *")
    print("      *")
    print(" * * *")
elif N == 6:
    print(" * * *")
    print("*")
    print("*")
    print("*")
    print(" * * *")
    print("*     *")
    print("*     *")
    print("*     *")
    print(" * * *")
elif N == 7:
    print(" * * *")
    print("      *")
    print("      *")
    print("      *")
    print()
    print("      *")
    print("      *")
    print("      *")
    print()
elif N == 8:
    print(" * * *")
    print("*     *")
    print("*     *")
    print("*     *")
    print(" * * *")
    print("*     *")
    print("*     *")
    print("*     *")
    print(" * * *")
elif N == 9:
    print(" * * *")
    print("*     *")
    print("*     *")
    print("*     *")
    print(" * * *")
    print("      *")
    print("      *")
    print("      *")
    print(" * * *")
